### DISCUSSION TITLE
Github: stack PR workflow and prevent merging stack into one another

### DISCUSSION THREAD

**Discussion by OlivierLDff** [gitext-rs/git-stack#343] [General]
Hi, I'm using stack PR workflow for github.

I have the assle of manually choosing the base branch in github, I don't have anything to help with that yet.

I want to share a simple action I added that fix a big pain-point in the workflow: Merging a PR into another. Often a coworker would review my stack into the wrong order, and I would see a big green ready to merge button. If not paying attention that the PR base branch isn't `main`, I could merge a PR into another branch, creating a mess, and not clean commit history in `main`.

So here I present to you an action that will prevent you from merging by making the CI failing and adding a `🗄️ stacked` label to the PR automatically.

```yml
name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.base_ref }} != "main" ]; then
            echo "Pull requests can only be merged in main. This is to avoid stack pr to be merged in wrong branch"
            gh pr edit ${{ github.event.pull_request.number }} --add-label "🗄️ stacked"
            exit 1
          fi
          gh pr edit ${{ github.event.pull_request.number }} --remove-label "🗄️ stacked" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
```

Example:
![image](https://github.com/gitext-rs/git-stack/assets/17255804/de57511b-4cee-42fc-ba1d-e2dc24f41a1d)

As you can see the label is automatically added and removed from the PR.

Then on my first PR targeting `main`:
![image](https://github.com/gitext-rs/git-stack/assets/17255804/44b9d7c5-e20b-4368-b094-60097cadd3eb)
And the subsequent one:
![image](https://github.com/gitext-rs/git-stack/assets/17255804/75491bc1-a16c-4b69-ba60-c93cc846ae0a)

Have a nice day, I hope this action could help someone in their workflow, and whatnot if someone has improvement

EDIT:
## CLI workflow

I found some nice CLI tricks to ease the workflow.

Create the PR on github based on the correct branch:

```bash
gh pr create --base $(git stack --format list --stack current | tail -n 2 | head -n 1) --fill
```

Force push all branchs of a stack:
```bash
git push origin $(git stack --format list --stack all) --force
```
